export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";


export const AUTH_USER_REQUEST = "AUTH_USER_REQUEST";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAIL = "AUTH_USER_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL";

export const ACCOUNT_DISABLE_SUCCESS = "ACCOUNT_DISABLE_SUCCESS";
export const ACCOUNT_DISABLE_FAIL = "ACCOUNT_DISABLE_FAIL";

export const ACCOUNT_DELETE_SUCCESS = "ACCOUNT_DELETE_SUCCESS";
export const ACCOUNT_DELETE_FAIL = "ACCOUNT_DELETE_FAIL";


export const CREATE_TAG_REQUEST = "CREATE_TAG_REQUEST";
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const CREATE_TAG_FAIL = "CREATE_TAG_FAIL";
export const CREATE_TAG_RESET = "CREATE_TAG_RESET";


export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";


export const UPDATE_ACCOUNT_REQUEST = "UPDATE_ACCOUNT_REQUEST";
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";
export const UPDATE_ACCOUNT_FAIL = "UPDATE_ACCOUNT_FAIL";
export const UPDATE_ACCOUNT_RESET = "UPDATE_ACCOUNT_RESET";

export const UPDATE_NOTIFICATION_SETTING_REQUEST = "UPDATE_NOTIFICATION_SETTING_REQUEST";
export const UPDATE_NOTIFICATION_SETTING_SUCCESS = "UPDATE_NOTIFICATION_SETTING_SUCCESS";
export const UPDATE_NOTIFICATION_SETTING_FAIL = "UPDATE_NOTIFICATION_SETTING_FAIL";
export const UPDATE_NOTIFICATION_SETTING_RESET = "UPDATE_NOTIFICATION_SETTING_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

