export const MEMORIES_REQUEST = "MEMORIES_REQUEST";
export const MEMORIES_SUCCESS = "MEMORIES_SUCCESS";
export const MEMORIES_FAIL = "MEMORIES_FAIL";
export const MEMORIES_RESET = "MEMORIES_RESET";


export const MEMORY_REPOST_REQUEST = "MEMORY_REPOST_REQUEST";
export const MEMORY_REPOST_SUCCESS = "MEMORY_REPOST_SUCCESS";
export const MEMORY_REPOST_FAIL = "MEMORY_REPOST_FAIL";
export const MEMORY_REPOST_RESET = "MEMORY_REPOST_RESET";

export const MEMORIES_TIMELINE = "MEMORIES_TIMELINE_SUCCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

