export const POSTS_REQUEST = "POSTS_REQUEST";
export const POSTS_SUCCESS = "POSTS_SUCCESS";
export const POSTS_FAIL = "POSTS_FAIL";
export const POSTS_RESET = "POSTS_RESET";

export const FOLLOWING_POSTS_REQUEST = "FOLLOWING_POSTS_REQUEST";
export const FOLLOWING_POSTS_SUCCESS = "FOLLOWING_POSTS_SUCCESS";
export const FOLLOWING_POSTS_FAIL = "FOLLOWING_POSTS_FAIL";
export const FOLLOWING_POSTS_RESET = "FOLLOWING_POSTS_RESET";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const CREATE_POST_RESET = "CREATE_POST_RESET";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";
export const UPDATE_POST_RESET = "UPDATE_POST_RESET";


export const SINGLE_POST_REQUEST = "SINGLE_POST_REQUEST";
export const SINGLE_POST_SUCCESS = "SINGLE_POST_SUCCESS";
export const SINGLE_POST_FAIL = "SINGLE_POST_FAIL";
export const SINGLE_POST_RESET = "SINGLE_POST_RESET";


export const VIEW_POST_REQUEST = "VIEW_POST_REQUEST";
export const VIEW_POST_SUCCESS = "VIEW_POST_SUCCESS";
export const VIEW_POST_FAIL = "VIEW_POST_FAIL";
export const VIEW_POST_RESET = "VIEW_POST_RESET";


export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";
export const DELETE_POST_RESET = "DELETE_POST_RESET";






export const CLEAR_ERRORS = "CLEAR_ERRORS";

