export const VIEW_POST_REQUEST = "VIEW_POST_REQUEST";
export const VIEW_POST_SUCCESS = "VIEW_POST_SUCCESS";
export const VIEW_POST_FAIL = "VIEW_POST_FAIL";
export const VIEW_POST_RESET = "VIEW_POST_RESET";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";
export const LIKE_POST_RESET = "LIKE_POST_RESET";

export const UNLIKE_POST_REQUEST = "UNLIKE_POST_REQUEST";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";
export const UNLIKE_POST_FAIL = "UNLIKE_POST_FAIL";
export const UNLIKE_POST_RESET = "UNLIKE_POST_RESET";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
export const CREATE_COMMENT_RESET = "CREATE_COMMENT_RESET";

export const LIKE_COMMENT_REQUEST = "LIKE_COMMENT_REQUEST";
export const LIKE_COMMENT_SUCCESS = "LIKE_COMMENT_SUCCESS";
export const LIKE_COMMENT_FAIL = "LIKE_COMMENT_FAIL";
export const LIKE_COMMENT_RESET = "LIKE_COMMENT_RESET";

export const UNLIKE_COMMENT_REQUEST = "UNLIKE_COMMENT_REQUEST";
export const UNLIKE_COMMENT_SUCCESS = "UNLIKE_COMMENT_SUCCESS";
export const UNLIKE_COMMENT_FAIL = "UNLIKE_COMMENT_FAIL";
export const UNLIKE_COMMENT_RESET = "UNLIKE_COMMENT_RESET";


export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET";

export const SHEET_OPEN = "SHEET_OPEN";
export const SHEET_CLOSE = "SHEET_CLOSE";



export const ADD_DIAMOND_IN_POST_REQUEST = "ADD_DIAMOND_IN_POST_REQUEST";
export const ADD_DIAMOND_IN_POST_SUCCESS = "ADD_DIAMOND_IN_POST_SUCCESS";
export const ADD_DIAMOND_IN_POST_FAIL = "ADD_DIAMOND_IN_POST_FAIL";
export const ADD_DIAMOND_IN_POST_RESET = "ADD_DIAMOND_IN_POST_RESET";



export const SHARE_POST_REQUEST = "SHARE_POST_REQUEST";
export const SHARE_POST_SUCCESS = "SHARE_POST_SUCCESS";
export const SHARE_POST_FAIL = "SHARE_POST_FAIL";
export const SHARE_POST_RESET = "SHARE_POST_RESET";



export const ADD_DIAMOND_INTO_POST_REQUEST = "ADD_DIAMOND_INTO_POST_REQUEST";
export const ADD_DIAMOND_INTO_POST_SUCCESS = "ADD_DIAMOND_INTO_POST_SUCCESS";
export const ADD_DIAMOND_INTO_POST_FAIL = "ADD_DIAMOND_INTO_POST_FAIL";
export const ADD_DIAMOND_INTO_POST_RESET = "ADD_DIAMOND_INTO_POST_RESET";

export const ONE_MINUT_REWARD_REQUEST = "ONE_MINUT_REWARD_REQUEST";
export const ONE_MINUT_REWARD_SUCCESS = "ONE_MINUT_REWARD_SUCCESS";
export const ONE_MINUT_REWARD_FAIL = "ONE_MINUT_REWARD_FAIL";
export const ONE_MINUT_REWARD_RESET = "ONE_MINUT_REWARD_RESET";


export const REPORT_POST_REQUEST = "REPORT_POST_REQUEST";
export const REPORT_POST_SUCCESS = "REPORT_POST_SUCCESS";
export const REPORT_POST_FAIL = "REPORT_POST_FAIL";
export const REPORT_POST_RESET = "REPORT_POST_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

