export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";
export const SEARCH_RESET = "SEARCH_RESET";

export const SEARCH_TIMELINE = "SEARCH_TIMELINE_SUCCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

