export const HELP_AND_SUPPORT_REQUEST = "HELP_AND_SUPPORT_REQUEST";
export const HELP_AND_SUPPORT_SUCCESS = "HELP_AND_SUPPORT_SUCCESS";
export const HELP_AND_SUPPORT_FAIL = "HELP_AND_SUPPORT_FAIL";
export const HELP_AND_SUPPORT_RESET = "HELP_AND_SUPPORT_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

