export const SUGGESSION_REQUEST = "SUGGESSION_REQUEST";
export const SUGGESSION_SUCCESS = "SUGGESSION_SUCCESS";
export const SUGGESSION_FAIL = "SUGGESSION_FAIL";
export const SUGGESSION_RESET = "SUGGESSION_RESET";

export const FOLLOW_REQUEST = "FOLLOW_REQUEST";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_FAIL = "FOLLOW_FAIL";
export const FOLLOW_RESET = "FOLLOW_RESET";

export const UNFOLLOW_REQUEST = "UNFOLLOW_REQUEST";
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";
export const UNFOLLOW_FAIL = "UNFOLLOW_FAIL";
export const UNFOLLOW_RESET = "UNFOLLOW_RESET";

export const HIDE_NOTIFICATION_REQUEST = "HIDE_NOTIFICATION_REQUEST";
export const HIDE_NOTIFICATION_SUCCESS = "HIDE_NOTIFICATION_SUCCESS";
export const HIDE_NOTIFICATION_FAIL = "HIDE_NOTIFICATION_FAIL";
export const HIDE_NOTIFICATION_RESET = "HIDE_NOTIFICATION_RESET";

export const UPDATE_FCM_REQUEST = "UPDATE_FCM_REQUEST";
export const UPDATE_FCM_SUCCESS = "UPDATE_FCM_SUCCESS";
export const UPDATE_FCM_FAIL = "UPDATE_FCM_FAIL";
export const UPDATE_FCM_RESET = "UPDATE_FCM_RESET";

export const PROMPT_OPEN = "PROMPT_OPEN";
export const PROMPT_CLOSE = "PROMPT_CLOSE";


export const CLEAR_ERRORS = "CLEAR_ERRORS";

